- name: Copy Mongodb Repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB Client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: latest

- name: Load Schema
  ansible.builtin.shell: mongo --host mongodb-dev.sushma1923.pics <${app_path}/schema/{{ component }}.js