- name: Install Mysql Client
  ansible.builtin.yum:
    name: mysql
    state: latest

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-dev.sushma1923.pics -uroot -pRoboShop@1 < /app/schema/{{ component }}.sql